### ISSUE TITLE
Parallelization

### ISSUE THREAD

**Issue by mdnunez** [tmiasko/pyjags#1]
Will the parallelization of chains be incorporated into pyjags in the future? Or is another Python module for using multiple cores with pyjags recommended?

Thank you.

**Comment by tmiasko** [comment]
Functionality to run chains in parallel is on list of features that I would
like to add to pyjags. 

At the moment I think that you could use multiprocessing or even threading
package from standard library with different model instances and RNG seeds.
Though, I must say I didn't try it yet.

Threading should work because I already wrote a part of the code that releases
the global interpreter lock before sampling starts in JAGS.

**Comment by tmiasko** [comment]
I added some threading support, it is available on git master branch, but is
not released yet. Number of threads can be specified using threads keyword
argument (defaults to 1). Unless customized further, each chain creates a
separate JAGS model, this can be controlled using chains_per_thread.

Though, I must say that performance improvement is not that great. It seems
that JAGS works better when sampling from multiple chains at once.

**Comment by mdnunez** [comment]
Thank you. I got 4 threads working with one chain each. It was significantly faster (10,000 samples per chain ran in 13 seconds) than 4 chains non-paralleled (10,000 samples per chain ran in 37 seconds) in an initial test when fitting simulated data from a diffusion model using the jags-wiener package:
http://sourceforge.net/projects/jags-wiener/

The parallelization should be very useful when fitting hierarchical models.

**Comment by tmiasko** [comment]
Great to hear that it worked much better with your model. I published pyjags
with thread support on pip as 1.1.0.
